### ISSUE TITLE
css note

### ISSUE THREAD

**Issue by zwwtj2014** [zwwtj2014/blogs#7]

**Comment by zwwtj2014** [comment]
## [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display)

每个元素都有这个属性：

> block: 块级元素 div, p 、 form, header 、 footer 、 section等等
inline: 行内元素 a
none: 一般script标签，用于不显示。

none和 visibility 属性不一样。**把 display 设置成 none 元素不会占据它本来应该显示的空间，但是设置成 visibility: hidden; 还会占据空间。**

**Comment by zwwtj2014** [comment]
```css
#main{
  width: 600px;
  margin: 0 auto;
}
```

**Comment by zwwtj2014** [comment]
盒子模型中padding会在设置width的基础上撑大盒子。可以使用` box-sizing: border-box; `来解决这个问题，以width为值，朝内括

```css
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```
`

**Comment by zwwtj2014** [comment]
## postion

>static(default)：表示元素不会被特殊的定位

>relative：relative 表现的和 static 一样，除非你添加了一些额外的属性。比如设置top left等等。**他的元素的位置则不会受该元素的影响发生位置改变来弥补它偏离后剩下的空隙。**

>fixed：**相对于视窗固定**。一个固定定位元素不会保留它原本在页面应有的空隙（脱离文档流）。一般用来做固定导航，或者广告。也可以设置top left bottom right。。

>absolute：基本的意思和fixed的一样。**但值得注意的是固定不是相对于视窗，而是相对于最近的一个具有position的元素，没有的话就是相对于body**

**Comment by zwwtj2014** [comment]
## float && clear && overflow

float会使dom浮动，其它的文字啥的都围绕着这个dom布局。
使用`clear:both`清除这种浮动

---

在使用浮动的时候，可以出现float的图片比较大超过包含它的dom的情况，我们需要使用overflow来hack解决：
```css
.clearfix {
  overflow: auto;
}
```

**Comment by zwwtj2014** [comment]
## inline-block

>1、vertical-align 属性会影响到 inline-block 元素，你可能会把它的值设置为 top 
2、你需要设置每一列的宽度
3、如果HTML源代码中元素之间有空格，那么列与列之间会产生空隙

**Comment by zwwtj2014** [comment]
## column

可以方便界面布局设置列数，跟新闻报纸很像
```css
.three-column {
  padding: 1em;
  -moz-column-count: 3;
  -moz-column-gap: 1em;
  -webkit-column-count: 3;
  -webkit-column-gap: 1em;
  column-count: 3;
  column-gap: 1em;
}
```
